[package]
name = "stan-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
stan-ast.workspace = true
stan-autodiff.workspace = true
stan-parser.workspace = true
thiserror.workspace = true
serde_json = { workspace = true, optional = true }
rand.workspace = true
rand_distr = "0.6"

[features]
default = ["json"]
json = ["dep:serde_json"]
